import SwiftUI
import Combine

class LocalizationManager: ObservableObject {
    static let shared = LocalizationManager()
    
    @AppStorage("appLanguage") var language: String = "en"
    
    private let translations: [String: [String: String]] = [
        // English
        "en": [
            "app.name": "TransPop",
            "onboarding.title": "Permissions Required",
            "onboarding.desc": "TransPop needs Accessibility permissions to detect the global shortcut (Cmd+C+C) and read the selected text.",
            "onboarding.granted": "Permissions Granted!",
            "onboarding.restart_required": "Restart Required",
            "onboarding.restart_desc": "Please restart the app to apply changes.",
            "onboarding.restart_desc_macos": "macOS may require a restart to detect the new permissions.",
            "onboarding.btn.quit_restart": "Quit & Restart",
            "onboarding.btn.force_start": "Force Start (I'm sure)",
            "onboarding.btn.open_settings": "Open System Settings",
            "onboarding.instruction": "Go to Privacy & Security > Accessibility and enable TransPop",
            "onboarding.btn.manual_confirm": "I have enabled permissions",
            
            "settings.title": "Settings",
            "settings.language": "Language",
            "settings.general": "General",
            "settings.quit": "Quit TransPop",
            "settings.theme": "Theme",
            "theme.system": "System",
            "theme.light": "Light",
            "theme.dark": "Dark",
            
            "main.detect_language": "Detect Language",
            "main.placeholder.source": "Enter text to translate...",
            "main.placeholder.target": "Translation will appear here...",
            "main.copy": "Copy",
            "main.clear": "Clear",
            "main.read_aloud": "Read Aloud",
            "main.stop_speaking": "Stop Speaking",
            
            "lang.en": "English",
            "lang.zh-CN": "Chinese (Simplified)",
            "lang.zh-TW": "Chinese (Traditional)",
            "lang.ja": "Japanese",
            "lang.ko": "Korean",
            "lang.fr": "French",
            "lang.de": "German",
            "lang.es": "Spanish",
            
            "settings.close_action": "When closing window",
            "settings.close.prompt": "Ask every time",
            "settings.close.minimize": "Minimize to tray",
            "settings.close.quit": "Quit application",
            
            "settings.provider": "Provider",
            "settings.api_url": "API URL",
            "settings.api_key": "API Key",
            "settings.model": "Model",
            "settings.api_key_placeholder": "Optional for local",
            "settings.provider.google": "Google (Free)",
            "settings.provider.bing": "Bing Translate (Free)",
            "settings.provider.openai": "OpenAI Compatible (Advanced)",
            
            "settings.updates": "Updates",
            "settings.updates.auto": "Automatically check for updates",
            "settings.updates.check": "Check for Updates",
            "settings.updates.checking": "Checking...",
            "settings.updates.latest": "Latest version installed",
            "settings.updates.new_version": "New version available:",
            "settings.updates.download": "Download & Install"
        ],
        // Chinese Simplified
        "zh-CN": [
            "app.name": "TransPop",
            "onboarding.title": "需要权限",
            "onboarding.desc": "TransPop 需要辅助功能权限来检测全局快捷键 (Cmd+C+C) 并读取选中的文本。",
            "onboarding.granted": "权限已授予！",
            "onboarding.restart_required": "需要重启",
            "onboarding.restart_desc": "请重启应用以应用更改。",
            "onboarding.restart_desc_macos": "macOS 可能需要重启才能检测到新权限。",
            "onboarding.btn.quit_restart": "退出并重启",
            "onboarding.btn.force_start": "强制启动 (我确定)",
            "onboarding.btn.open_settings": "打开系统设置",
            "onboarding.instruction": "前往 隐私与安全性 > 辅助功能 并启用 TransPop",
            "onboarding.btn.manual_confirm": "我已经启用了权限",
            
            "settings.title": "设置",
            "settings.language": "语言",
            "settings.general": "常规",
            "settings.quit": "退出 TransPop",
            "settings.theme": "外观",
            "theme.system": "跟随系统",
            "theme.light": "浅色",
            "theme.dark": "深色",
            
            "main.detect_language": "检测语言",
            "main.placeholder.source": "输入要翻译的文本...",
            "main.placeholder.target": "翻译结果将显示在这里...",
            "main.copy": "复制",
            "main.clear": "清除",
            "main.read_aloud": "朗读",
            "main.stop_speaking": "停止朗读",
            
            "lang.en": "英语",
            "lang.zh-CN": "中文 (简体)",
            "lang.zh-TW": "中文 (繁体)",
            "lang.ja": "日语",
            "lang.ko": "韩语",
            "lang.fr": "法语",
            "lang.de": "德语",
            "lang.es": "西班牙语",
            
            "settings.close_action": "关闭窗口时",
            "settings.close.prompt": "每次询问",
            "settings.close.minimize": "最小化到托盘",
            "settings.close.quit": "退出应用",
            
            "settings.provider": "翻译服务",
            "settings.api_url": "API 地址",
            "settings.api_key": "API 密钥",
            "settings.model": "模型名称",
            "settings.api_key_placeholder": "本地部署可留空",
            "settings.provider.google": "Google (免费)",
            "settings.provider.bing": "Bing 翻译 (免费)",
            "settings.provider.openai": "OpenAI 兼容 (高级)",
            
            "settings.updates": "更新",
            "settings.updates.auto": "自动检查更新",
            "settings.updates.check": "检查更新",
            "settings.updates.checking": "正在检查...",
            "settings.updates.latest": "已是最新版本",
            "settings.updates.new_version": "发现新版本：",
            "settings.updates.download": "下载并安装"
        ],
        // Chinese Traditional
        "zh-TW": [
            "app.name": "TransPop",
            "onboarding.title": "需要權限",
            "onboarding.desc": "TransPop 需要輔助功能權限來檢測全局快捷鍵 (Cmd+C+C) 並讀取選中的文本。",
            "onboarding.granted": "權限已授予！",
            "onboarding.restart_required": "需要重啟",
            "onboarding.restart_desc": "請重啟應用以應用更改。",
            "onboarding.restart_desc_macos": "macOS 可能需要重啟才能檢測到新權限。",
            "onboarding.btn.quit_restart": "退出並重啟",
            "onboarding.btn.force_start": "強制啟動 (我確定)",
            "onboarding.btn.open_settings": "打開系統設置",
            "onboarding.instruction": "前往 隱私與安全性 > 輔助功能 並啟用 TransPop",
            "onboarding.btn.manual_confirm": "我已經啟用了權限",
            
            "settings.title": "設置",
            "settings.language": "語言",
            "settings.general": "常規",
            "settings.quit": "退出 TransPop",
            "settings.theme": "外觀",
            "theme.system": "跟隨系統",
            "theme.light": "淺色",
            "theme.dark": "深色",
            
            "main.detect_language": "檢測語言",
            "main.placeholder.source": "輸入要翻譯的文本...",
            "main.placeholder.target": "翻譯結果將顯示在這裡...",
            "main.copy": "複製",
            "main.clear": "清除",
            "main.read_aloud": "朗讀",
            "main.stop_speaking": "停止朗讀",
            
            "lang.en": "英語",
            "lang.zh-CN": "中文 (簡體)",
            "lang.zh-TW": "中文 (繁體)",
            "lang.ja": "日語",
            "lang.ko": "韓語",
            "lang.fr": "法語",
            "lang.de": "德語",
            "lang.es": "西班牙語",
            
            "settings.close_action": "關閉視窗時",
            "settings.close.prompt": "每次詢問",
            "settings.close.minimize": "最小化到托盤",
            "settings.close.quit": "退出應用",
            
            "settings.provider": "翻譯服務",
            "settings.api_url": "API 地址",
            "settings.api_key": "API 金鑰",
            "settings.model": "模型名稱",
            "settings.api_key_placeholder": "本地部署可留空",
            "settings.provider.google": "Google (免費)",
            "settings.provider.bing": "Bing 翻譯 (免費)",
            "settings.provider.openai": "OpenAI 相容 (進階)",
            
            "settings.updates": "更新",
            "settings.updates.auto": "自動檢查更新",
            "settings.updates.check": "檢查更新",
            "settings.updates.checking": "正在檢查...",
            "settings.updates.latest": "已是最新版本",
            "settings.updates.new_version": "發現新版本：",
            "settings.updates.download": "下載並安裝"
        ],
        // Japanese
        "ja": [
            "app.name": "TransPop",
            "onboarding.title": "権限が必要です",
            "onboarding.desc": "TransPop は、グローバルショートカット (Cmd+C+C) を検出し、選択したテキストを読み取るためにアクセシビリティ権限が必要です。",
            "onboarding.granted": "権限が付与されました！",
            "onboarding.restart_required": "再起動が必要です",
            "onboarding.restart_desc": "変更を適用するにはアプリを再起動してください。",
            "onboarding.restart_desc_macos": "macOS は新しい権限を検出するために再起動が必要な場合があります。",
            "onboarding.btn.quit_restart": "終了して再起動",
            "onboarding.btn.force_start": "強制起動 (確認済み)",
            "onboarding.btn.open_settings": "システム設定を開く",
            "onboarding.instruction": "プライバシーとセキュリティ > アクセシビリティ に移動し、TransPop を有効にしてください",
            "onboarding.btn.manual_confirm": "権限を有効にしました",
            
            "settings.title": "設定",
            "settings.language": "言語",
            "settings.general": "一般",
            "settings.quit": "TransPop を終了",
            "settings.theme": "テーマ",
            "theme.system": "システム",
            "theme.light": "ライト",
            "theme.dark": "ダーク",
            
            "main.detect_language": "言語を検出",
            "main.placeholder.source": "翻訳するテキストを入力...",
            "main.placeholder.target": "翻訳結果がここに表示されます...",
            "main.copy": "コピー",
            "main.clear": "クリア",
            "main.read_aloud": "読み上げ",
            "main.stop_speaking": "読み上げ停止",
            
            "lang.en": "英語",
            "lang.zh-CN": "中国語 (簡体字)",
            "lang.zh-TW": "中国語 (繁体字)",
            "lang.ja": "日本語",
            "lang.ko": "韓国語",
            "lang.fr": "フランス語",
            "lang.de": "ドイツ語",
            "lang.es": "スペイン語",
            
            "settings.close_action": "ウィンドウを閉じる時",
            "settings.close.prompt": "毎回確認する",
            "settings.close.minimize": "トレイに最小化",
            "settings.close.quit": "アプリを終了",
            
            "settings.provider": "翻訳プロバイダー",
            "settings.api_url": "API URL",
            "settings.api_key": "API キー",
            "settings.model": "モデル名",
            "settings.api_key_placeholder": "ローカルの場合は省略可",
            "settings.provider.google": "Google (無料)",
            "settings.provider.bing": "Bing 翻訳 (無料)",
            "settings.provider.openai": "OpenAI 互換 (詳細)",
            
            "settings.updates": "アップデート",
            "settings.updates.auto": "自動的にアップデートを確認",
            "settings.updates.check": "アップデートを確認",
            "settings.updates.checking": "確認中...",
            "settings.updates.latest": "最新バージョンです",
            "settings.updates.new_version": "新しいバージョン：",
            "settings.updates.download": "ダウンロードしてインストール"
        ],
        // Korean
        "ko": [
            "app.name": "TransPop",
            "onboarding.title": "권한 필요",
            "onboarding.desc": "TransPop은 전역 단축키(Cmd+C+C)를 감지하고 선택한 텍스트를 읽으려면 손쉬운 사용 권한이 필요합니다.",
            "onboarding.granted": "권한 허용됨!",
            "onboarding.restart_required": "재시작 필요",
            "onboarding.restart_desc": "변경 사항을 적용하려면 앱을 다시 시작하십시오.",
            "onboarding.restart_desc_macos": "macOS에서 새 권한을 감지하려면 재시작이 필요할 수 있습니다.",
            "onboarding.btn.quit_restart": "종료 및 재시작",
            "onboarding.btn.force_start": "강제 시작 (확인함)",
            "onboarding.btn.open_settings": "시스템 설정 열기",
            "onboarding.instruction": "개인정보 보호 및 보안 > 손쉬운 사용으로 이동하여 TransPop을 활성화하십시오",
            "onboarding.btn.manual_confirm": "권한을 활성화했습니다",
            
            "settings.title": "설정",
            "settings.language": "언어",
            "settings.general": "일반",
            "settings.quit": "TransPop 종료",
            "settings.theme": "테마",
            "theme.system": "시스템",
            "theme.light": "라이트",
            "theme.dark": "다크",
            
            "main.detect_language": "언어 감지",
            "main.placeholder.source": "번역할 텍스트 입력...",
            "main.placeholder.target": "번역 결과가 여기에 표시됩니다...",
            "main.copy": "복사",
            "main.clear": "지우기",
            "main.read_aloud": "읽기",
            "main.stop_speaking": "읽기 중지",
            
            "lang.en": "영어",
            "lang.zh-CN": "중국어 (간체)",
            "lang.zh-TW": "중국어 (번체)",
            "lang.ja": "일본어",
            "lang.ko": "한국어",
            "lang.fr": "프랑스어",
            "lang.de": "독일어",
            "lang.es": "스페인어",
            
            "settings.close_action": "창을 닫을 때",
            "settings.close.prompt": "항상 묻기",
            "settings.close.minimize": "트레이로 최소화",
            "settings.close.quit": "앱 종료",
            
            "settings.provider": "번역 제공자",
            "settings.api_url": "API URL",
            "settings.api_key": "API 키",
            "settings.model": "모델 이름",
            "settings.api_key_placeholder": "로컬인 경우 선택 사항",
            "settings.provider.google": "Google (무료)",
            "settings.provider.bing": "Bing 번역 (무료)",
            "settings.provider.openai": "OpenAI 호환 (고급)",
            
            "settings.updates": "업데이트",
            "settings.updates.auto": "자동으로 업데이트 확인",
            "settings.updates.check": "업데이트 확인",
            "settings.updates.checking": "확인 중...",
            "settings.updates.latest": "최신 버전입니다",
            "settings.updates.new_version": "새 버전 사용 가능:",
            "settings.updates.download": "다운로드 및 설치"
        ],
        // French
        "fr": [
            "app.name": "TransPop",
            "onboarding.title": "Permissions requises",
            "onboarding.desc": "TransPop a besoin des permissions d'accessibilité pour détecter le raccourci global (Cmd+C+C) et lire le texte sélectionné.",
            "onboarding.granted": "Permissions accordées !",
            "onboarding.restart_required": "Redémarrage requis",
            "onboarding.restart_desc": "Veuillez redémarrer l'application pour appliquer les changements.",
            "onboarding.restart_desc_macos": "macOS peut nécessiter un redémarrage pour détecter les nouvelles permissions.",
            "onboarding.btn.quit_restart": "Quitter et redémarrer",
            "onboarding.btn.force_start": "Forcer le démarrage (Je suis sûr)",
            "onboarding.btn.open_settings": "Ouvrir les réglages système",
            "onboarding.instruction": "Allez dans Confidentialité et sécurité > Accessibilité et activez TransPop",
            "onboarding.btn.manual_confirm": "J'ai activé les permissions",
            
            "settings.title": "Paramètres",
            "settings.language": "Langue",
            "settings.general": "Général",
            "settings.quit": "Quitter TransPop",
            "settings.theme": "Thème",
            "theme.system": "Système",
            "theme.light": "Clair",
            "theme.dark": "Sombre",
            
            "main.detect_language": "Détecter la langue",
            "main.placeholder.source": "Entrez le texte à traduire...",
            "main.placeholder.target": "La traduction apparaîtra ici...",
            "main.copy": "Copier",
            "main.clear": "Effacer",
            "main.read_aloud": "Lire à haute voix",
            "main.stop_speaking": "Arrêter la lecture",
            
            "lang.en": "Anglais",
            "lang.zh-CN": "Chinois (Simplifié)",
            "lang.zh-TW": "Chinois (Traditionnel)",
            "lang.ja": "Japonais",
            "lang.ko": "Coréen",
            "lang.fr": "Français",
            "lang.de": "Allemand",
            "lang.es": "Espagnol",
            
            "settings.close_action": "À la fermeture de la fenêtre",
            "settings.close.prompt": "Demander à chaque fois",
            "settings.close.minimize": "Réduire dans la barre d'état",
            "settings.close.quit": "Quitter l'application",
            
            "settings.provider": "Fournisseur",
            "settings.api_url": "URL de l'API",
            "settings.api_key": "Clé API",
            "settings.model": "Modèle",
            "settings.api_key_placeholder": "Optionnel pour local",
            "settings.provider.google": "Google (Gratuit)",
            "settings.provider.bing": "Bing Traduction (Gratuit)",
            "settings.provider.openai": "Compatible OpenAI (Avancé)",
            
            "settings.updates": "Mises à jour",
            "settings.updates.auto": "Vérifier automatiquement",
            "settings.updates.check": "Vérifier les mises à jour",
            "settings.updates.checking": "Vérification...",
            "settings.updates.latest": "Dernière version installée",
            "settings.updates.new_version": "Nouvelle version disponible :",
            "settings.updates.download": "Télécharger et installer"
        ],
        // German
        "de": [
            "app.name": "TransPop",
            "onboarding.title": "Berechtigungen erforderlich",
            "onboarding.desc": "TransPop benötigt Zugriffsberechtigungen, um die globale Tastenkombination (Cmd+C+C) zu erkennen und den ausgewählten Text zu lesen.",
            "onboarding.granted": "Berechtigungen erteilt!",
            "onboarding.restart_required": "Neustart erforderlich",
            "onboarding.restart_desc": "Bitte starten Sie die App neu, um die Änderungen zu übernehmen.",
            "onboarding.restart_desc_macos": "macOS erfordert möglicherweise einen Neustart, um die neuen Berechtigungen zu erkennen.",
            "onboarding.btn.quit_restart": "Beenden & Neustarten",
            "onboarding.btn.force_start": "Start erzwingen (Ich bin sicher)",
            "onboarding.btn.open_settings": "Systemeinstellungen öffnen",
            "onboarding.instruction": "Gehen Sie zu Datenschutz & Sicherheit > Bedienungshilfen und aktivieren Sie TransPop",
            "onboarding.btn.manual_confirm": "Ich habe die Berechtigungen aktiviert",
            
            "settings.title": "Einstellungen",
            "settings.language": "Sprache",
            "settings.general": "Allgemein",
            "settings.quit": "TransPop beenden",
            "settings.theme": "Thema",
            "theme.system": "System",
            "theme.light": "Hell",
            "theme.dark": "Dunkel",
            
            "main.detect_language": "Sprache erkennen",
            "main.placeholder.source": "Text zum Übersetzen eingeben...",
            "main.placeholder.target": "Die Übersetzung erscheint hier...",
            "main.copy": "Kopieren",
            "main.clear": "Löschen",
            "main.read_aloud": "Vorlesen",
            "main.stop_speaking": "Vorlesen stoppen",
            
            "lang.en": "Englisch",
            "lang.zh-CN": "Chinesisch (Vereinfacht)",
            "lang.zh-TW": "Chinesisch (Traditionell)",
            "lang.ja": "Japanisch",
            "lang.ko": "Koreanisch",
            "lang.fr": "Französisch",
            "lang.de": "Deutsch",
            "lang.es": "Spanisch",
            
            "settings.close_action": "Beim Schließen des Fensters",
            "settings.close.prompt": "Jedes Mal fragen",
            "settings.close.minimize": "In Systemtray minimieren",
            "settings.close.quit": "Anwendung beenden",
            
            "settings.provider": "Anbieter",
            "settings.api_url": "API URL",
            "settings.api_key": "API Schlüssel",
            "settings.model": "Modell",
            "settings.api_key_placeholder": "Optional für lokal",
            "settings.provider.google": "Google (Kostenlos)",
            "settings.provider.bing": "Bing Translate (Kostenlos)",
            "settings.provider.openai": "OpenAI Kompatibel (Erweitert)",
            
            "settings.updates": "Updates",
            "settings.updates.auto": "Automatisch nach Updates suchen",
            "settings.updates.check": "Nach Updates suchen",
            "settings.updates.checking": "Suchen...",
            "settings.updates.latest": "Neueste Version installiert",
            "settings.updates.new_version": "Neue Version verfügbar:",
            "settings.updates.download": "Herunterladen & Installieren"
        ],
        // Spanish
        "es": [
            "app.name": "TransPop",
            "onboarding.title": "Permisos requeridos",
            "onboarding.desc": "TransPop necesita permisos de accesibilidad para detectar el atajo global (Cmd+C+C) y leer el texto seleccionado.",
            "onboarding.granted": "¡Permisos concedidos!",
            "onboarding.restart_required": "Reinicio requerido",
            "onboarding.restart_desc": "Reinicie la aplicación para aplicar los cambios.",
            "onboarding.restart_desc_macos": "macOS puede requerir un reinicio para detectar los nuevos permisos.",
            "onboarding.btn.quit_restart": "Salir y reiniciar",
            "onboarding.btn.force_start": "Forzar inicio (Estoy seguro)",
            "onboarding.btn.open_settings": "Abrir configuración del sistema",
            "onboarding.instruction": "Vaya a Privacidad y seguridad > Accesibilidad y habilite TransPop",
            "onboarding.btn.manual_confirm": "He habilitado los permisos",
            
            "settings.title": "Configuración",
            "settings.language": "Idioma",
            "settings.general": "General",
            "settings.quit": "Salir de TransPop",
            "settings.theme": "Tema",
            "theme.system": "Sistema",
            "theme.light": "Claro",
            "theme.dark": "Oscuro",
            
            "main.detect_language": "Detectar idioma",
            "main.placeholder.source": "Ingrese texto para traducir...",
            "main.placeholder.target": "La traducción aparecerá aquí...",
            "main.copy": "Copiar",
            "main.clear": "Borrar",
            "main.read_aloud": "Leer en voz alta",
            "main.stop_speaking": "Dejar de leer",
            
            "lang.en": "Inglés",
            "lang.zh-CN": "Chino (Simplificado)",
            "lang.zh-TW": "Chino (Tradicional)",
            "lang.ja": "Japonés",
            "lang.ko": "Coreano",
            "lang.fr": "Francés",
            "lang.de": "Alemán",
            "lang.es": "Español",
            
            "settings.close_action": "Al cerrar la ventana",
            "settings.close.prompt": "Preguntar siempre",
            "settings.close.minimize": "Minimizar a la bandeja",
            "settings.close.quit": "Salir de la aplicación",
            
            "settings.provider": "Proveedor",
            "settings.api_url": "URL de la API",
            "settings.api_key": "Clave API",
            "settings.model": "Modelo",
            "settings.api_key_placeholder": "Opcional para local",
            "settings.provider.google": "Google (Gratis)",
            "settings.provider.bing": "Bing Translate (Gratis)",
            "settings.provider.openai": "Compatible con OpenAI (Avanzado)",
            
            "settings.updates": "Actualizaciones",
            "settings.updates.auto": "Buscar actualizaciones automáticamente",
            "settings.updates.check": "Buscar actualizaciones",
            "settings.updates.checking": "Buscando...",
            "settings.updates.latest": "Última versión instalada",
            "settings.updates.new_version": "Nueva versión disponible:",
            "settings.updates.download": "Descargar e instalar"
        ]
    ]
    
    func localizedString(_ key: String) -> String {
        let dict = translations[language] ?? translations["en"]!
        return dict[key] ?? key
    }
}

// Helper extension for easier usage in SwiftUI
extension String {
    var localized: String {
        return LocalizationManager.shared.localizedString(self)
    }
}
